SELECT
	D@STS STATUS,
	D1INPO# ORDERNUMBER,
	D1INORD# REFERENCENUMBER,
	D1INLINE LINENUMBER,
	D1INMFGR||D1INCOLO||D1INPATT ITEMNUMBER,
	D1INMFGR MANUFACTURER,
	D1INMFGR||D1IPRODL PRODUCTLINE,
	D1IXSER# SERIALNUMBER,
	D1INCO#ACC ACCOUNT,
	D1INCUPO CUSTOMERPO,
	D1INQTYO QUANTITY,
	D1IXLOC# BINLOCATION,
	D1HNAME SHIPTONAME,
	D1HCITY SHIPTOCITY,
	D1HSTATE SHIPTOSTATE
FROM QS36F.OPENPO@H H
	INNER JOIN QS36F.OPENPO@D D ON H@REF# = D@REF# AND H@ORD# = D@ORD#
	INNER JOIN QS36F.DW0001F DW ON D1INPO# = H@REF# AND D1INORD# = H@ORD# AND D1INLINE =D@LINE
	LEFT JOIN ISCLIB.VLMORDERS VLM ON H@REF# = VOORDER AND H@ORD# = VOREF AND D@LINE = VOLINE AND VOTYPE = 'I'
WHERE H@ROLOVR <> 'Y'
	AND VOORDER IS NULL
	AND D1INREF# = 0
	AND D1INACCT > 3
	AND D1INDATISO = INT(CURRENT_DATE)
	AND D1INWAREDT IN('LDC','SAM')
	AND D@STS = 'L'
	AND D1IXLOC# IN('VLM1','VLM2')
	AND D@DEL8 <> '#'
ORDER BY H@REF#, D@LINE