SELECT
    NREF# INVREF,
    NLINE# INVLINE,
    NPO# ORDERNUMBER,
    NMFGR||NCOLOR||NPAT ITEMNUMBER,
    NSER# SERIALNUMBER,
    NLOC# LDCLOCATION,
    NRECEI QUANTITY
FROM QS36F.OPENIV
WHERE NDATE = INT(CURRENT_DATE) AND NREFTY = 'R'
