SELECT
	NREFTY STATUS,
    NDATE ORDERDATE,
	NPO# ORDERNUMBER,
	NREF# REFERENCENUMBER,
	NLINE# LINENUMBER,
	NMFGR||NCOLOR||NPAT ITEMNUMBER,
	NMFGR MANUFACTURER,
	IMFGR||IPRODL PRODUCTLINE,
	NSER# SERIALNUMBER,
	'' ACCOUNT,
	'' CUSTOMERPO,
	NRECEI QUANTITY,
	NLOC# BINLOCATION,
	'' SHIPTONAME,
	'' SHIPTOCITY,
	'' SHIPTOSTATE
FROM QS36F.OPENIV OIV
	LEFT JOIN QS36F.ITEM ITM ON IMFGR||ICOLOR||IPATT = NMFGR||NCOLOR||NPAT
	LEFT JOIN ISCLIB.VLMORDERS VLM ON VOORDER = NPO# AND VOREF = NREF# AND VOLINE = NLINE# AND VOTYPE = 'R'
WHERE VOORDER IS NULL 
	AND NREFTY = 'R'
	AND NWARE# IN('LDC','SAM')
	AND NLOC# IN('VLM1','VLM2')
ORDER BY NPO#, NLINE#